#!/bin/bash

# Creates a new tmux session for app development

STRIPE_HOOK_URL=localhost:5001/farm-troy/us-central1/stripeHook

if [ ! -z "$1" ]; then
    session_name=$1
else
    session_name=$(basename $PWD)
fi

# check if session already exists, attach if it does
tmux has-session -t $session_name 2>/dev/null
if [ $? -eq 0 ]; then
    tmux attach-session -t $session_name
    exit
fi

# create session and open bash
tmux new-session -d -s $session_name -n code -c $PWD

# open code
tmux send-keys -t code "nvim ." C-m

# watch
tmux new-window -b -t code -c $PWD -n watch 
tmux send-keys "cd functions" C-m
tmux send-keys "npm run build:watch"
tmux split-window -h
tmux send-keys "dart run build_runner watch --delete-conflicting-outputs"

# run
tmux new-window -b -t code -c $PWD -n run
tmux send-keys "flutter run"
tmux split-window -h
tmux send-keys "firebase emulators:start --import firebase-export"
tmux split-window -v
tmux send-keys "stripe listen --forward-to $STRIPE_HOOK_URL"

# commands
tmux new-window -a -t code -c $PWD -n commands

# switch to code window
tmux select-window -t code

# attach to session
tmux attach-session -t $session_name
