#!/bin/sh

# Create a tmux session with a general development environment

# require session name
if [ ! -z "$1" ]; then
    session_name=$1
else
    session_name=$(basename $PWD)
fi

echo session name: $session_name

# attach to session if it already exists
tmux has-session -t $session_name 2>/dev/null
if [ $? -eq 0 ]; then
    echo Session already exists, attaching...
    tmux attach-session -t $session_name
    exit
fi

echo Creating new session...
tmux new-session -d -s $session_name -n code -c $PWD
tmux send-keys -t code "nvim ." C-m
tmux new-window -b -t code -c $PWD -n run
tmux new-window -a -t code -c $PWD
tmux select-window -t code
tmux attach-session -t $session_name

